---
- name: Install repository
  hosts: openio
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-repository

- name: Install netdata on monitored nodes
  hosts: netdata
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-netdata
  tags:
    - netdata

- name: Install blackbox
  hosts: blackbox
  become: true
  gather_facts: true
  roles:
    - ansible-blackbox-exporter
  tags:
    - blackbox

- name: Install prometheus
  hosts: admin:openio
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-prometheus
  tags:
    - prometheus

- name: Install alertmanager
  hosts: alertmanager
  become: true
  gather_facts: true
  roles:
    - role: ansible-alertmanager
  tags:
    - alertmanager

- name: Install NTP server
  hosts: prometheus
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-ntp
  tags:
    - prometheus

- name: Install grafana
  hosts: grafana
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-grafana
  tags:
    - grafana
...
